//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NabeatsuGenerator.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NabeatsuGenerator.SourceGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   NabeatsuAttribute を付与するメソッドは partial でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO001Format {
            get {
                return ResourceManager.GetString("AHO001Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AHO001 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO001Title {
            get {
                return ResourceManager.GetString("AHO001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NabeatsuAttribute の start パラメーターの値（{0}）は 0 以上でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO002Format {
            get {
                return ResourceManager.GetString("AHO002Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AHO002 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO002Title {
            get {
                return ResourceManager.GetString("AHO002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NabeatsuAttribute の end パラメーターの値（{0}）は start パラメーターの値（{1}）以上でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO003Format {
            get {
                return ResourceManager.GetString("AHO003Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AHO003 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO003Title {
            get {
                return ResourceManager.GetString("AHO003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NabeatsuAttribute を付与するメソッドの戻り値は IEnumerable&lt;string&gt; でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO004Format {
            get {
                return ResourceManager.GetString("AHO004Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AHO004 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AHO004Title {
            get {
                return ResourceManager.GetString("AHO004Title", resourceCulture);
            }
        }
    }
}
